-- Migration: 009_create_billing_events
-- One billing event per org per billing period (daily or monthly).
-- Generated by the billing background worker from usage_aggregates.

CREATE TABLE IF NOT EXISTS billing_events (
    id                UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    org_id            UUID        NOT NULL REFERENCES organizations(id),
    period_start      TIMESTAMPTZ NOT NULL,
    period_end        TIMESTAMPTZ NOT NULL,

    -- Usage breakdown for this period
    total_requests    INT         NOT NULL,
    total_tokens      BIGINT      NOT NULL,
    total_energy_kwh  REAL        NOT NULL,
    total_co2e_grams  REAL        NOT NULL,

    -- Pricing
    subtotal_usd      REAL        NOT NULL,
    discount_percent  REAL        NOT NULL DEFAULT 0,
    total_usd         REAL        NOT NULL,

    -- Lifecycle
    status            VARCHAR(20) NOT NULL DEFAULT 'pending',  -- pending, invoiced, paid, overdue
    invoice_url       VARCHAR(500),

    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_billing_org ON billing_events(org_id, period_start DESC);
