apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecollm-staging

resources:
  - ../../base

namePrefix: staging-

commonLabels:
  env: staging

patches:
  - target:
      kind: Deployment
      name: ecollm-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: ecollm-web
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  - target:
      kind: Deployment
      name: ecollm-inference-gateway
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
