-- EcoLLM canonical schema (auto-generated reference — authoritative source is db/migrations/)
-- This file is regenerated by: pg_dump --schema-only ecollm > db/schema.sql
-- DO NOT edit manually; edit the migration files instead.

-- Run migrations: make migrate
-- Seed data:      make seed
